name: Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install docs dependencies
        run: pip install -r requirements-docs.txt
      - name: Build docs with mkdocs
        run: cd docs && mkdocs build
      - name: Upload documentation site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs/build/html

  deploy:
    name: Deploy on GitHub Pages
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write # IMPORTANT: mandatory for GitHub Pages branch
    steps:
      - uses: actions/checkout@v4
      - name: Download documentation site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: docs/build/html
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
