name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and check distribution package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install build dependencies
        run: pip install build twine
      - name: Run build
        run: python -mbuild
      - name: Run twine check
        run: python -mtwine check dist/*
      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: py-dist
          path: dist/

  security:
    name: Security check
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install pip-audit
        run: pip install pip-audit~=2.7
      - name: Run pip-audit
        run: pip-audit --aliases --skip-editable .

  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    name: Pytest (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install project
        run: pip install .
      - name: Install test dependencies
        run: pip install -r requirements-tests.txt
      - run: mkdir coverage
      - name: Run tests with coverage
        run: pytest --ignore tests/test_e2e.py
        env:
          COVERAGE_FILE: coverage/.coverage.py${{ matrix.python-version }}
      - name: Upload coverage result
        uses: actions/upload-artifact@v4
        with:
          name: coverage-py${{ matrix.python-version }}
          path: coverage

  coverage-combine:
    name: Combine coverages
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install coverage
        run: pip install coverage[toml]
      - name: Download coverage files
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-py*
          path: coverage
          merge-multiple: true
      - run: coverage combine coverage
      - run: coverage report
      - run: coverage html -d htmlcov
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
